name: Update Search Index

on:
  push:
    paths:
      - 'contents/docs/**' # Trigger only when docs change
  workflow_dispatch: # Allows manual triggering

jobs:
  build-search-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run search index build
        run: npm run build:search

      - name: Commit and push updated index
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/search-index.json
          git commit -m "Auto-update search index [skip ci]" || exit 0
          git push
